name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install mkdocs
      run: pip3 install mkdocs==1.6.1

    - name: build
      run: make
