name: mkdocs

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 12 * * *' # Every day noon UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install mkdocs
      run: pip3 install mkdocs==1.6.1

    - name: build
      run: make
